### PR TITLE
Use arrays instead of ptrs for fixed len strings

### PR DESCRIPTION
**Pull request by moonsdad**
string name<NAME_LEN> becomes a char*
As it is when we declare a message on the stack and initialize it with string literals, the pointer will point to read only memory in the text section. If we use an array, we can initialize it with a literal but still have the memory on the stack.

Another benefit is the ability to use sizeof(message) to get the actual size of a message.

### CODE REVIEW

**Comment by apexskier** [comment]
Lets wait to merge before bringing this up in class.

**Comment by apexskier** [comment]
I think using the rpc string type might be semantically better (and I've already got it working like that and don't want to have to change it 😬). But, if other people want to change to this I can do it.

**Comment by moonsdad** [comment]
If we use pointers then the issue becomes: who does the work of padding,  the client or the server?

**Comment by apexskier** [comment]
The server always does the work before saving. The client just sends a message object across and the server deals with it, regardless of what it looks like. Also, remember that any client can send data to your server, so it has to deal with potentially unpadded data.

In my implementation, I'm actually using fixed length arrays with the current version of the spec, just statically allocating them in the client.

**Comment by moonsdad** [comment]
We also have to remember that any server could be handling the clients requests. I'd rather let rpcgen do the work for me than do it myself twice. Still, It's a simple enough assignment that I won't complain about the extra work.

 I'm getting around my issue by changing

    message template = {
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 0,
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    };

into

    char to[NAME_LEN] =
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";
    char from[NAME_LEN] =
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";
    char mesg[MSG_LEN] =
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
        "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    message template = { to, from, 0, mesg };

**Comment by apexskier** [comment]
I'm doing mine much differently.

```c
message msg_w; // writable message
char msg_to[NAME_LEN];
char msg_from[NAME_LEN];
char msg_content[MSG_LEN];
msg_w.to = msg_to;
msg_w.from = msg_from;
msg_w.content = msg_content;   
/*...*/
memset(msg->from, '\0', NAME_LEN);
```

**Comment by moonsdad** [comment]
It's basically the same thing. You're just assigning the elements one at a time and initializing more robustly with an extra procedure call. I think I'll get rid of the initialization and let strncpy fill in the padding, since it will do so automatically anyway.

**Pull request merged**
