### PR TITLE
Update database description

### PR DESCRIPTION
**Pull request by moonsdad**
Lets say we have 9998 messages in a database for some user. No messages have yet been retrieved.
tims_namez of that user will have a value of "00009999". Now, when we want to deposit another message at index 9999 we cannot because "0000" == "0000". So then, we can only ever have 9998 messages, and the wasted one isn't always "0000" as was initially suggested by our instructor.

### CODE REVIEW

**Comment by moonsdad** [comment]
I was trying to merge your changes to my fork, before sending this pull request. But, hopefully you can see the changes I intended. I think the description update will help others understand.

**Comment by moonsdad** [comment]
I see that some of the changes I made are already included. To make this easier, will you give me permissions to make a branch and then I can delete my fork? Though, there's probably nothing more I'm thinking of suggesting.

**Comment by apexskier** [comment]
You're a collaborator. Go ahead and merge these changes once fixed, they all look good to me.

**Comment by moonsdad** [comment]
Thanks. Changes have been merged.

**Pull request closed without merging**
